### PR TITLE
[MASTER BRANCH] Add new AddLogEntrycommand with Ui implementation

### LINKED ISSUE #251: Add Log only accepts log entry inline, without formatting

### PR DESCRIPTION
**Pull request by slidings**
closes #251 
New command allows users to use the keyword "addentry" to call a popup to enter their logs in a textbox rather in than in line. New line formating will be preserved and "\n" will be recognised as new line. 

Use `addentry i/NRIC d/DATE`

Known bugs
1. Certain formats of \n will cause it to be passed to AddLogCommand as actual formatting. Currently replacing all "\n" with "\\n" but there is still bugs

Styling is yet to be done

### CODE REVIEW

**Comment by zhiyi12345** [comment]
one thing I noticed that could be done better is to keep in the string within the box limit instead scrolling horizontally.

appreciate how enter goes to new line--> but another problem is user need to press the save button to save? I tried toggling with keyboard, but I can't seem to save when I press enter

**Comment by zhiyi12345** [comment]
/n seems to work as expected for addlog

**Comment by slidings** [comment]
> one thing I noticed that could be done better is to keep in the string within the box limit instead scrolling horizontally.
> 
> appreciate how enter goes to new line--> but another problem is user need to press the save button to save? I tried toggling with keyboard, but I can't seem to save when I press enter

Fixes:
1. The window now has auto warping enabled
2. Window will have minimum size to prevent funny formatting when its shrinked too much
3. Added shortcut to save. (Ctrl + Enter or CMD + Enter)

Rationale behind double key is to prevent accidental presses

**Comment by zhiyi12345** [comment]
LGTM!

**Pull request merged**
